-- AlterTable
ALTER TABLE `accounts` MODIFY `status` ENUM('UNACTIVE', 'ACTIVE', 'COLD', 'BANNED') NOT NULL DEFAULT 'UNACTIVE';

-- AlterTable
ALTER TABLE `users` MODIFY `status` ENUM('UNACTIVE', 'ACTIVE', 'COLD', 'BANNED') NOT NULL DEFAULT 'UNACTIVE';
